version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
